info:
  name: deleteEnvironment/{id}
  type: http
  seq: 2

http:
  method: DELETE
  url: "{{http_url}}/v1/environments/{{environment_id}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
