name: production
variables:
  - name: http_protocol
    value: https
  - name: http_port
    value: "443"
  - name: http_host
    value: api.viplev.ringhus.dk
  - name: http_url
    value: "{{http_protocol}}://{{http_host}}:{{http_port}}"
  - secret: true
    name: agent_access_token
  - name: benchmark_id
    value: ""
  - name: run_id
    value: ""
  - secret: true
    name: access_token
